// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	addProject: (path: string, onlyCli: boolean | null) => typedError<Project, AppError>(__TAURI_INVOKE("add_project", { path, onlyCli })),
	removeProject: (projectId: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_project", { projectId })),
	removePackage: (projectId: string, packageName: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_package", { projectId, packageName })),
	listProjects: () => typedError<Project[], AppError>(__TAURI_INVOKE("list_projects")),
	refreshProject: (projectId: string, onlyCli: boolean) => typedError<Project, AppError>(__TAURI_INVOKE("refresh_project", { projectId, onlyCli })),
	scanProject: (path: string) => typedError<PackageInfo[], string>(__TAURI_INVOKE("scan_project", { path })),
	checkPackageCli: (path: string) => __TAURI_INVOKE<boolean>("check_package_cli", { path }),
	createSandbox: (packagePath: string | null) => typedError<string, AppError>(__TAURI_INVOKE("create_sandbox", { packagePath })),
	runSandboxScript: (targetPath: string) => typedError<string, AppError>(__TAURI_INVOKE("run_sandbox_script", { targetPath })),
	runWorkspaceTask: (projectId: string, task: string) => typedError<string, AppError>(__TAURI_INVOKE("run_workspace_task", { projectId, task })),
	runPackageTask: (projectId: string, packageName: string, task: string) => typedError<string, AppError>(__TAURI_INVOKE("run_package_task", { projectId, packageName, task })),
	getPackageScripts: (path: string) => typedError<ScriptInfo[], AppError>(__TAURI_INVOKE("get_package_scripts", { path })),
	runSecurityAudit: (projectId: string) => typedError<string, string>(__TAURI_INVOKE("run_security_audit", { projectId })),
	getDirectorySize: (path: string) => typedError<number | null, string>(__TAURI_INVOKE("get_directory_size", { path })),
	getDirectorySizes: (paths: string[]) => typedError<{ [key in string]: number | null }, string>(__TAURI_INVOKE("get_directory_sizes", { paths })),
	detectPackageManager: (path: string) => typedError<PackageManagerInfo, AppError>(__TAURI_INVOKE("detect_package_manager", { path })),
	getPackageInfo: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("get_package_info", { path })),
	npmPackDryRun: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("npm_pack_dry_run", { path })),
	createLink: (request: LinkRequest) => typedError<LinkEntry, AppError>(__TAURI_INVOKE("create_link", { request })),
	removeLink: (linkId: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_link", { linkId })),
	listActiveLinks: () => typedError<LinkEntry[], AppError>(__TAURI_INVOKE("list_active_links")),
	toggleLinkWatch: (linkId: string, enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("toggle_link_watch", { linkId, enabled })),
	getWatchCommand: (sourcePath: string) => typedError<string | null, AppError>(__TAURI_INVOKE("get_watch_command", { sourcePath })),
	linkViaSymlink: (source: string, target: string) => typedError<string, AppError>(__TAURI_INVOKE("link_via_symlink", { source, target })),
	linkViaPack: (source: string, target: string) => typedError<string, AppError>(__TAURI_INVOKE("link_via_pack", { source, target })),
	linkViaYalc: (source: string, target: string) => typedError<string, AppError>(__TAURI_INVOKE("link_via_yalc", { source, target })),
	linkViaWorkspace: (source: string, target: string) => typedError<string, AppError>(__TAURI_INVOKE("link_via_workspace", { source, target })),
	startWatching: (linkId: string, path: string) => typedError<null, string>(__TAURI_INVOKE("start_watching", { linkId, path })),
	stopWatching: (linkId: string) => typedError<null, string>(__TAURI_INVOKE("stop_watching", { linkId })),
	getWatcherStatus: () => typedError<{ [key in string]: boolean }, string>(__TAURI_INVOKE("get_watcher_status")),
	runBuild: (path: string, script: string | null) => typedError<string, AppError>(__TAURI_INVOKE("run_build", { path, script })),
	runInstall: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("run_install", { path })),
	startRegistry: (port: number | null) => typedError<string, string>(__TAURI_INVOKE("start_registry", { port })),
	stopRegistry: () => typedError<null, string>(__TAURI_INVOKE("stop_registry")),
	publishToRegistry: (packagePath: string, registryUrl: string | null, dryRun: boolean | null) => typedError<string, string>(__TAURI_INVOKE("publish_to_registry", { packagePath, registryUrl, dryRun })),
	listRegistryPackages: (registryUrl: string | null) => typedError<string[], string>(__TAURI_INVOKE("list_registry_packages", { registryUrl })),
	getRegistryStatus: () => typedError<RegistryStatus, string>(__TAURI_INVOKE("get_registry_status")),
	runDiagnostics: () => typedError<DiagnosticResult[], string>(__TAURI_INVOKE("run_diagnostics")),
	checkSymlinkPermissions: () => typedError<DiagnosticResult, string>(__TAURI_INVOKE("check_symlink_permissions")),
	checkNodeInstallation: () => typedError<DiagnosticResult, string>(__TAURI_INVOKE("check_node_installation")),
	exportDiagnostics: () => typedError<string, string>(__TAURI_INVOKE("export_diagnostics")),
	getConfig: () => typedError<AppConfig, string>(__TAURI_INVOKE("get_config")),
	saveConfig: (config: AppConfig) => typedError<null, string>(__TAURI_INVOKE("save_config", { config })),
	getLogs: () => __TAURI_INVOKE<LogEntry[]>("get_logs"),
	clearLogs: () => __TAURI_INVOKE<void>("clear_logs"),
	openFolderDialog: () => typedError<string | null, string>(__TAURI_INVOKE("open_folder_dialog")),
	openTerminal: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_terminal", { path })),
	openInExplorer: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_in_explorer", { path })),
	openUrl: (url: string) => typedError<null, string>(__TAURI_INVOKE("open_url", { url })),
	getSystemInfo: () => typedError<SystemInfo, string>(__TAURI_INVOKE("get_system_info")),
	getFilteredEnvVars: () => __TAURI_INVOKE<string[]>("get_filtered_env_vars"),
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
	spawnPty: (sessionId: string, directory: string, cols: number, rows: number) => typedError<null, string>(__TAURI_INVOKE("spawn_pty", { sessionId, directory, cols, rows })),
	writePty: (sessionId: string, data: string) => typedError<null, string>(__TAURI_INVOKE("write_pty", { sessionId, data })),
	resizePty: (sessionId: string, rows: number, cols: number) => typedError<null, string>(__TAURI_INVOKE("resize_pty", { sessionId, rows, cols })),
	killPty: (sessionId: string) => typedError<null, string>(__TAURI_INVOKE("kill_pty", { sessionId })),
	attachPty: (sessionId: string) => typedError<string | null, string>(__TAURI_INVOKE("attach_pty", { sessionId })),
	getAnalyticsSummary: () => typedError<AnalyticsSummary, string>(__TAURI_INVOKE("get_analytics_summary")),
	recordTaskExecution: (scriptName: string, durationMs: number) => typedError<null, string>(__TAURI_INVOKE("record_task_execution", { scriptName, durationMs })),
};

/* Types */
export type AnalyticsSummary = {
	total_tasks_run: number,
	total_duration_ms: number,
};

export type AppConfig = {
	general: GeneralConfig,
	registry: RegistryConfig,
	watcher: WatcherConfig,
	appearance: AppearanceConfig,
};

export type AppError = string;

export type AppearanceConfig = {
	theme: string,
	sidebar_collapsed: boolean,
};

export type Dependency = {
	name: string,
	version: string,
	is_local: boolean,
};

export type DiagnosticResult = {
	category: string,
	check: string,
	status: DiagnosticStatus,
	message: string,
	fix_suggestion: string | null,
	fix_command: string | null,
};

export type DiagnosticStatus = "Pass" | "Warning" | "Fail";

export type GeneralConfig = {
	default_package_manager: string,
	auto_build_on_link: boolean,
	auto_install_deps: boolean,
	projects_directory: string | null,
	/**
	 *  SECURITY: when false (default), every link/install command runs with
	 *  `--ignore-scripts` so a linked package's postinstall/prepare/prepack
	 *  scripts never execute. See services/link.rs.
	 */
	allow_lifecycle_scripts?: boolean,
};

export type LinkEntry = {
	id: string,
	source_package: string,
	source_path: string,
	target_project: string,
	target_path: string,
	method: LinkMethod,
	status: LinkStatus,
	watch_enabled: boolean,
	created_at: string,
	last_synced: string | null,
	has_cli?: boolean,
};

export type LinkMethod = "Symlink" | "NpmPack" | "Yalc" | "Workspace" | "LocalRegistry" | "FileCopy";

export type LinkRequest = {
	source_path: string,
	target_path: string,
	method: LinkMethod,
	watch: boolean,
	build_first: boolean,
	install_peer_deps: boolean,
	allow_lifecycle_scripts?: boolean,
};

export type LinkStatus = "Active" | "Broken" | "Syncing" | { Error: string } | "Inactive";

export type LogEntry = {
	id: string,
	timestamp: string,
	level: LogLevel,
	message: string,
	source: string,
};

export type LogLevel = "info" | "warning" | "error" | "success";

export type PackageInfo = {
	name: string,
	version: string,
	path: string,
	is_private: boolean,
	dependencies: Dependency[],
	dev_dependencies: Dependency[],
	peer_dependencies: Dependency[],
	has_cli?: boolean,
};

export type PackageManager = "Npm" | "Yarn" | "Pnpm" | "Bun" | "Unknown";

export type PackageManagerInfo = {
	detected: PackageManager,
	version: string | null,
	lock_file: string | null,
};

export type Project = {
	id: string,
	name: string,
	path: string,
	package_manager: PackageManager,
	packages: PackageInfo[],
	ignored_packages?: string[],
	only_cli?: boolean,
	workspace_tool?: WorkspaceTool,
	created_at: string,
	last_accessed: string,
};

export type RegistryConfig = {
	port: number,
	storage_path: string,
	auto_start: boolean,
};

export type RegistryStatus = {
	running: boolean,
	pid: number | null,
};

export type ScriptInfo = {
	name: string,
	command: string,
	is_lifecycle: boolean,
	risk_level: string,
	threat_categories: string[],
	risk_explanation: string | null,
};

export type SystemInfo = {
	os: string,
	arch: string,
	node_version: string,
	npm_version: string,
	yarn_version: string | null,
	pnpm_version: string | null,
};

export type WatcherConfig = {
	debounce_ms: number,
	ignore_patterns: string[],
	auto_rebuild: boolean,
};

export type WorkspaceTool = "Turbo" | "Lerna" | "Pnpm" | "Yarn" | "Npm" | "None";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

